# Generated by Django 3.0.5 on 2020-04-13 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Harga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rumput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_rumput', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Waktu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.CharField(max_length=100)),
                ('harga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lapangan.Harga')),
            ],
        ),
        migrations.CreateModel(
            name='Lapangan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('gambar', models.ImageField(blank=True, default='images/lapangan/no_img.jpeg', upload_to='images/lapangan/')),
                ('jenis_rumput', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lapangan.Rumput')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('lapangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lapangan.Lapangan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('waktu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lapangan.Waktu')),
            ],
        ),
    ]
