# Generated by Django 3.0.4 on 2020-03-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapangan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lapangan',
            name='gambar',
            field=models.ImageField(default='images/lapangan/no_img.jpeg', upload_to='images/lapangan/'),
        ),
    ]
