# Generated by Django 3.0.5 on 2020-04-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapangan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waktu',
            name='waktu',
            field=models.CharField(max_length=100),
        ),
    ]
