# Generated by Django 3.0.5 on 2020-04-13 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lapangan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='tanggal',
            field=models.DateField(),
        ),
    ]
