# Generated by Django 3.0.4 on 2020-03-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapangan', '0002_lapangan_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lapangan',
            name='gambar',
            field=models.ImageField(default='lapangan/no_img.jpeg', upload_to='lapangan/'),
        ),
    ]
