# Generated by Django 3.0.5 on 2020-04-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapangan', '0003_booking_kode_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='kode_booking',
            field=models.CharField(default='A8A0D', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='waktu',
        ),
        migrations.AddField(
            model_name='booking',
            name='waktu',
            field=models.ManyToManyField(to='lapangan.Waktu'),
        ),
    ]
