# Generated by Django 3.0.5 on 2020-04-05 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lapangan', '0004_harga_nama'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwal',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
