# Generated by Django 3.0.6 on 2020-06-02 08:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(default='B7E41', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
