# Generated by Django 3.0.6 on 2020-06-06 02:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='point',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
