# Generated by Django 3.0.6 on 2020-06-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20200602_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='point_required',
            field=models.DecimalField(decimal_places=0, default=100, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(default='81912', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='field',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
