# Generated by Django 3.0.6 on 2020-06-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20200604_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(default='E73C5', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.ManyToManyField(to='bookings.Time'),
        ),
    ]
