# Generated by Django 3.0.6 on 2020-06-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_auto_20200607_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(default='576-dc1', editable=False, max_length=50),
        ),
    ]
