# Generated by Django 3.0.7 on 2020-06-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_auto_20200607_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(default='6bc-6f1', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Selesai', 'Selesai'), ('Belum Selesai', 'Belum Selesai')], default='Belum Selesai', max_length=100),
        ),
    ]
