# Generated by Django 3.0.7 on 2020-06-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_auto_20200607_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(default='4c2-5a4', editable=False, max_length=50),
        ),
    ]
