# Generated by Django 3.0.7 on 2020-06-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_auto_20200607_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(default='7ad-a8b', editable=False, max_length=50),
        ),
    ]
