# Generated by Django 3.0.7 on 2020-06-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_auto_20200607_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(default='b34-614', editable=False, max_length=50),
        ),
    ]
