# Generated by Django 3.0.7 on 2020-06-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_auto_20200615_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(default='4AF-8F9', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Selesai', 'Selesai'), ('Pending', 'Pending'), ('Batal', 'Batal')], default='Pending', max_length=100),
        ),
    ]
